FROM golang:1.21.5

# Make directory for application
WORKDIR /webapi

# Download Go modules
COPY webapi/go.mod ./
RUN go mod download

# Copy the test code
COPY webapi/tests ./tests
RUN ls .

# Point d'entrée par défaut
CMD ["go", "test", "-v", "./tests/..."]
