FROM golang:1.21.5

# Make directory for application
WORKDIR /webapi

# Download Go modules
COPY webapi/go.mod ./
RUN go mod download

# Copy the source code
COPY webapi/tests/main_test.go ./
RUN ls ./tests

# Point d'entrée par défaut
CMD ["go", "test", "-v", "./tests/..."]
