apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: development
spec:
  selector:
    app: project-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: ClusterIP
