apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
  namespace: production
  labels:
    app: project-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
        - name: project-app-container
          image: efrei2023/s9_do_grp6_project:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: project-app
  namespace: production
  labels:
    app: project-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30080
  selector:
    app.kubernetes.io/name: project-app
